# Run tests on different OS/Python combinations
name: Conda-Matrix

on:
  pull_request:
    branches: master

jobs:
  conda:
    name: ${{ matrix.os }}-${{ matrix.CONDA_ENV }}-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        CONDA_ENV: [3.6, 3.7, 3.8]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v1
        with:
           environment-file: ci/environment-dev-py${{ matrix.CONDA_ENV }}.yml
           auto-activate-base: false
           activate-environment: dinosar
           miniconda-version: latest
           auto-update-conda: true

      - name: Install Dinosar From Latest Commit
        shell: bash -l {0}
        run: |
          conda --version
          python -m pip install .
          conda list

      - name: Run PyTest
        shell: bash -l {0}
        run: |
          pytest  -o markers=network -m "not network" --verbose --cov=dinosar --cov-report=xml
